FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install -y curl gnupg apt-transport-https wget iputils-ping dnsutils

RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

RUN curl -o /etc/apt/sources.list.d/microsoft.list "https://packages.microsoft.com/config/ubuntu/16.04/prod.list"

RUN apt-get update

RUN apt-get install -y mssql-cli