FROM mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04

USER root

RUN mkdir /opt/sqlserver
RUN mkdir /opt/sqlserver/data
RUN mkdir /opt/sqlserver/log
RUN mkdir /opt/sqlserver/backups

RUN chown -R mssql:mssql /opt/sqlserver
RUN chown -R mssql:mssql /var/opt/mssql

ENV ACCEPT_EULA="Y"
ENV MSSQL_PID="Developer"

USER mssql

CMD /opt/mssql/bin/sqlservr